"""The action ledger: agent_actions and action_audit_entries.

Revision ID: 0029
Revises: 0028
Create Date: 2026-08-24

Hand-written, not autogenerated. Autogenerate compares against the wrong search
path in this database and proposes dropping Langfuse's `monitors`,
`table_view_presets` and `default_llm_models`, which share it -- a generated
revision here takes three tables belonging to another product with it.

The downgrade drops both tables and the recorded actions in them. That is the
honest shape: there is nowhere else for those rows to live, and refusing to
downgrade while any exist would block a rollback during exactly the incident a
rollback is for. What it must not do is leave an index or a constraint behind,
which passes a shape check going down and fails going back up.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0029"
down_revision: str | None = "0028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "curie"


def upgrade() -> None:
    op.create_table(
        "agent_actions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("agent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("call_id", sa.String(), nullable=False),
        sa.Column("tool", sa.String(), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prior_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("dedupe_key", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("undone_at", sa.DateTime(), nullable=True),
        sa.Column("undone_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"], [f"{SCHEMA}.agents.id"], ondelete="CASCADE"
        ),
        sa.UniqueConstraint("dedupe_key"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_agent_actions_agent_id", "agent_actions", ["agent_id"], schema=SCHEMA
    )
    op.create_index(
        "ix_agent_actions_conversation_id",
        "agent_actions",
        ["conversation_id"],
        schema=SCHEMA,
    )
    op.create_index("ix_agent_actions_status", "agent_actions", ["status"], schema=SCHEMA)

    op.create_table(
        "action_audit_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("actor_channel", sa.String(), nullable=True),
        sa.Column("authorizer", sa.String(), nullable=False),
        sa.Column("authorized", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["action_id"], [f"{SCHEMA}.agent_actions.id"], ondelete="CASCADE"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_action_audit_entries_action_id",
        "action_audit_entries",
        ["action_id"],
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Audit rows first: they point at the actions, and CASCADE would take them
    # anyway, but an explicit order keeps the downgrade readable as the inverse.
    op.drop_index("ix_action_audit_entries_action_id", "action_audit_entries", schema=SCHEMA)
    op.drop_table("action_audit_entries", schema=SCHEMA)
    op.drop_index("ix_agent_actions_status", "agent_actions", schema=SCHEMA)
    op.drop_index("ix_agent_actions_conversation_id", "agent_actions", schema=SCHEMA)
    op.drop_index("ix_agent_actions_agent_id", "agent_actions", schema=SCHEMA)
    op.drop_table("agent_actions", schema=SCHEMA)
